name: Scan Proxy & Push Changes

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap jam 00:00 UTC (setiap 24 jam)
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

permissions:
  contents: write  # Memberikan izin untuk melakukan push

jobs:
  scan-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Sesuaikan dengan versi yang dibutuhkan

    - name: Run scan-proxy.py
      run: python3 ./scan2/scan-proxy2.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update proxyip" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/xuniversal/huntipcf.git main --force
